version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: compui
      MONGO_ENABLE_IPV6: yes
    networks:
      - mongo-network
  web:
    image: node:21-alpine
    command: sh -c "npm install && npm run dev"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./web:/app
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local